//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gr0ssSysTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gr0ssSysTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error_Caption {
            get {
                return ResourceManager.GetString("Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading your icon.
        ///Exception:
        ///.
        /// </summary>
        internal static string Error_Loading_Icon {
            get {
                return ResourceManager.GetString("Error_Loading_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Icon.
        /// </summary>
        internal static string Error_Loading_Icon_Caption {
            get {
                return ResourceManager.GetString("Error_Loading_Icon_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error retrieving the environment you selected..
        /// </summary>
        internal static string Error_Retrieving_Environment {
            get {
                return ResourceManager.GetString("Error_Retrieving_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Retrieving Environment.
        /// </summary>
        internal static string Error_Retrieving_Environment_Caption {
            get {
                return ResourceManager.GetString("Error_Retrieving_Environment_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error retrieving the tool you selected..
        /// </summary>
        internal static string Error_Retrieving_Tool {
            get {
                return ResourceManager.GetString("Error_Retrieving_Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Retrieving Tool.
        /// </summary>
        internal static string Error_Retrieving_Tool_Caption {
            get {
                return ResourceManager.GetString("Error_Retrieving_Tool_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception:.
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Exit_16 {
            get {
                object obj = ResourceManager.GetObject("Exit_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon folder_add {
            get {
                object obj = ResourceManager.GetObject("folder_add", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_add16 {
            get {
                object obj = ResourceManager.GetObject("folder_add16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Move_Arrow {
            get {
                object obj = ResourceManager.GetObject("Move_Arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Open_Folder {
            get {
                object obj = ResourceManager.GetObject("Open_Folder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open_Folder16 {
            get {
                object obj = ResourceManager.GetObject("Open_Folder16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open_Folder32 {
            get {
                object obj = ResourceManager.GetObject("Open_Folder32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure this is what you want to override the currently monitored registry key with?.
        /// </summary>
        internal static string Override_Registry_Key {
            get {
                return ResourceManager.GetString("Override_Registry_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue With Save.
        /// </summary>
        internal static string Override_Registry_Key_Caption {
            get {
                return ResourceManager.GetString("Override_Registry_Key_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select an environment before you can delete one....
        /// </summary>
        internal static string Select_Environment_To_Delete {
            get {
                return ResourceManager.GetString("Select_Environment_To_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Environment.
        /// </summary>
        internal static string Select_Environment_To_Delete_Caption {
            get {
                return ResourceManager.GetString("Select_Environment_To_Delete_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first select a valid modifier key..
        /// </summary>
        internal static string Select_Global_Hotkey_To_Save {
            get {
                return ResourceManager.GetString("Select_Global_Hotkey_To_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Finding Modifier Key.
        /// </summary>
        internal static string Select_Global_Hotkey_To_Save_Caption {
            get {
                return ResourceManager.GetString("Select_Global_Hotkey_To_Save_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first select a valid registry key..
        /// </summary>
        internal static string Select_Registry_Key {
            get {
                return ResourceManager.GetString("Select_Registry_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving Registry Key.
        /// </summary>
        internal static string Select_Registry_Key_Caption {
            get {
                return ResourceManager.GetString("Select_Registry_Key_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As this is your first time running the program, we need you to select the registry key you would like to monitor..
        /// </summary>
        internal static string Select_Registry_Key_To_Monitor {
            get {
                return ResourceManager.GetString("Select_Registry_Key_To_Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User Registry Monitoring Setup.
        /// </summary>
        internal static string Select_Registry_Key_To_Monitor_Caption {
            get {
                return ResourceManager.GetString("Select_Registry_Key_To_Monitor_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select a tool before you can delete one....
        /// </summary>
        internal static string Select_Tool_To_Delete {
            get {
                return ResourceManager.GetString("Select_Tool_To_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Tool.
        /// </summary>
        internal static string Select_Tool_To_Delete_Caption {
            get {
                return ResourceManager.GetString("Select_Tool_To_Delete_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Star_32 {
            get {
                object obj = ResourceManager.GetObject("Star_32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you selected doesn&apos;t appear to exist, please select a file that does..
        /// </summary>
        internal static string Tool_Doesnt_Exist {
            get {
                return ResourceManager.GetString("Tool_Doesnt_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File.
        /// </summary>
        internal static string Tool_Doesnt_Exist_Caption {
            get {
                return ResourceManager.GetString("Tool_Doesnt_Exist_Caption", resourceCulture);
            }
        }
    }
}
